services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: teamavail
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: teamavail
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: teamavail
      DB_PASSWORD: secret123
      DB_NAME: teamavail
    ports:
      - "3000:3000"

volumes:
  db-data:
  node_modules:
